### ISSUE TITLE
A question on the code

### ISSUE THREAD

**Issue by GoingMyWay** [Kiwoo/AveragedDQN-Implementation-using-PyTorch#1]
Hi, Kiwoo, thank you for sharing your code. I am new to Pytorch. In the Averaged DQN paper, Q^{A}_{i-1} is updated based on previously-updated `k` networks, and in `dqn.py`, line 108-110

    target_q_values = {}    
    for i in range(num_target_values):
        target_q_values[i] = q_func(input_arg, num_actions).type(dtype)

Does the above code represent the previously-updated `k` networks?  How can I do it with Tensorflow?

**Comment by Kiwoo** [comment]
Sorry, I honestly forget most of features about pyTorch.
I just wrote it for practicing pyTorch, but I turned back to Tensorflow.

**Comment by GoingMyWay** [comment]
@Kiwoo Thank you Kiwoo. I will close this issue.
